name: Firmware Build

on: push

jobs:
  build:
    name: Build firmware
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: arm-none-eabi-gcc GNU Arm Embedded Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1.10.1

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13' 

      - name: Checkout pico-sdk/2.2.0
        uses: actions/checkout@v4
        with:
          repository: raspberrypi/pico-sdk
          ref: 2.2.0
          path: /tmp/pico-sdk
          submodules: recursive

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Firmware
        id: build
        env:
          PICO_SDK_PATH: /tmp/pico-sdk
          PICO_COMPILER: arm-none-eabi-gcc
          SOURCE_DIR: firmware
          OUTPUT_DIR: build
          MAKEFILES_GENERATOR: "Unix Makefiles"
          CMAKE_ARGS: ""
          OUTPUT_IGNORED_DIRS: "CMakeFiles elf2uf2 pico-sdk pioasm"
          OUTPUT_EXT: "*.uf2 *.elf *.elf.map"
        run: |
          set -e

          # Make paths absolute
          OUTPUT_DIR_REL="$OUTPUT_DIR"
          SOURCE_DIR="$GITHUB_WORKSPACE/$SOURCE_DIR"
          OUTPUT_DIR="$GITHUB_WORKSPACE/$OUTPUT_DIR"

          rm -rf "$OUTPUT_DIR" && mkdir "$OUTPUT_DIR" && cd "$OUTPUT_DIR"
          cmake -S "$SOURCE_DIR" -B "$OUTPUT_DIR" -G "$MAKEFILES_GENERATOR" $CMAKE_ARGS

          echo "Building project..."
          # This causes create font_venv to be called 2x in parallel
          # cd "$OUTPUT_DIR" && make -j$(nproc)
          cd "$OUTPUT_DIR" && make

          # Split output extensions and into array
          IFS=" " read -r -a BINARY_EXTENSIONS <<< "$OUTPUT_EXT"

          # Split ignored build directories into array and append to IGNORED_BUILD_DIRS
          IFS=" " read -r -a IGNORED_BUILD_DIRS <<< "$OUTPUT_IGNORED_DIRS"

          # Remove ignored build directories
          echo "Removing unnecessary build directories..."
          for dir in "${IGNORED_BUILD_DIRS[@]}"; do
              if [ -d "$OUTPUT_DIR/$dir" ]; then
                  echo "Removing $dir..."
                  rm -rf "$OUTPUT_DIR/$dir"
              fi
          done

          echo "Moving build artifacts to output directory..."
          COPY_DEST_DIR="/tmp/make_build"
          for ext in "${BINARY_EXTENSIONS[@]}"; do
              find "$OUTPUT_DIR" -name "$ext" -print0 | while IFS= read -r -d '' file; do
                  echo "Copying $file..."
                  relative_path="${file#$OUTPUT_DIR/}"
                  mkdir -p "$COPY_DEST_DIR/$(dirname "$relative_path")"
                  cp "$file" "$COPY_DEST_DIR/$relative_path"
              done
          done

          # Clear the build directory
          echo "Clearing the build directory..."
          rm -rf "$OUTPUT_DIR" && mkdir "$OUTPUT_DIR"

          # Move the build artifacts back to the output directory
          echo "Moving build artifacts back to the output directory..."
          mv /tmp/make_build/* "$OUTPUT_DIR"

          echo "output_dir=$OUTPUT_DIR_REL" >> $GITHUB_OUTPUT

      # - name: Build Firmware
      #   id: build
      #   uses: ./.github/actions/pico-build-action
      #   with:
      #     source_dir: firmware
      #     output_ignored_dirs: font_venv

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: workspace_artifacts
          path: ${{steps.build.outputs.output_dir}}
