name: Firmware Build

on: push

jobs:
  build:
    name: Build firmware
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Firmware
        id: build
        uses: ./.github/actions/pico-build-action.yml
        with:
          source_dir: firmware
          output_ignored_dirs: font_venv

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: workspace_artifacts
          path: ${{steps.build.outputs.output_dir}}
