name: Firmware Build

on: push

jobs:
  build:
    name: Build firmware
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: arm-none-eabi-gcc GNU Arm Embedded Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1.10.1

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13' 

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Checkout pico-sdk/2.2.0
        uses: actions/checkout@v4
        with:
          repository: raspberrypi/pico-sdk
          ref: 2.2.0
          path: pico-sdk
          submodules: recursive

      - name: Build Firmware
        id: build
        env:
          PICO_SDK_PATH: ${{github.workspace}}/pico-sdk
          PICO_COMPILER: arm-none-eabi-gcc
          SOURCE_DIR: firmware
          OUTPUT_DIR: build
          MAKEFILES_GENERATOR: "Unix Makefiles"
          CMAKE_ARGS: ""
          OUTPUT_IGNORED_DIRS: "CMakeFiles elf2uf2 pico-sdk pioasm _deps"
          OUTPUT_EXT: "*.uf2 *.elf *.elf.map *.dis"
        run: |
          set -e

          # Make paths absolute
          OUTPUT_DIR_REL="$OUTPUT_DIR"
          SOURCE_DIR="$GITHUB_WORKSPACE/$SOURCE_DIR"
          OUTPUT_DIR="$GITHUB_WORKSPACE/$OUTPUT_DIR"

          rm -rf "$OUTPUT_DIR" && mkdir "$OUTPUT_DIR" && cd "$OUTPUT_DIR"
          cmake -S "$SOURCE_DIR" -B "$OUTPUT_DIR" -G "$MAKEFILES_GENERATOR" $CMAKE_ARGS

          echo "Building project..."
          # This causes create font_venv to be called 2x in parallel
          # cd "$OUTPUT_DIR" && make -j$(nproc)
          cd "$OUTPUT_DIR" && make

          echo "output_dir=$OUTPUT_DIR_REL" >> $GITHUB_OUTPUT

      # - name: Build Firmware
      #   id: build
      #   uses: ./.github/actions/pico-build-action
      #   with:
      #     source_dir: firmware
      #     output_ignored_dirs: font_venv

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build_artifacts
          path: |
            ${{steps.build.outputs.output_dir}}/*.uf2
            ${{steps.build.outputs.output_dir}}/*.elf
            ${{steps.build.outputs.output_dir}}/*.elf.map
            ${{steps.build.outputs.output_dir}}/*.dis

      - name: Upload UF2
        uses: actions/upload-artifact@v4
        with:
          name: firmware_binary
          path: ${{steps.build.outputs.output_dir}}/*.uf2
